version: '3.9'
services:
  # service:
  #   build: .
  #   ports:
  #     - '8080:8080'
  # depends_on:
  #   db:
  #     condition: service_healthy
  db:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', '127.0.0.1', '--silent']
      interval: 3s
      retries: 5
      start_period: 30s
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_DATABASE: goarsenal
